{% set name = "Phidget22" %}
{% set version = "1.19.20240311" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Phidget22-{{ version }}.tar.gz
  sha256: 1e22f95d805dab001f1e00868662b3d2b521ee54cc553f5259bc14720b91ffe3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - Phidget22
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://www.phidgets.com
  summary: Phidget22 Python wrapper library
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jjerphan
