{% set name = "Phidget22" %}
{% set version = "1.21.20241125" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.lower() }}-{{ version }}.tar.gz
  sha256: 3f3c20a249a16aed4e6d0d992974595315764c42d95fee95ae3670d46b76f1f0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - Phidget22
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://www.phidgets.com
  summary: Phidget22 Python wrapper library
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jjerphan
